# Preprocess 

Author: Yuxin Zhao

Last update: 25/08/2025

Dataset resources: West Midlands Fire Service (WMFS)

This notebook mainly focuses on:
 
1.	Data Preprocessing: Filter the West Midlands Fire Service (WMFS) incident dataset to retain only incidents classified as FIRE and FALSE_ALARM.

2.	Spatial Aggregation: Generate a 500-meter grid over the study area and spatially aggregate fire incidents within each grid cell.

3.	Timely Response Threshold: Define a timely fire response as one occurring within 300 seconds (5 minutes), in line with WMFS operational standards.

4.	Efficiency Metric: Develop a fire service efficiency metric based on the proportion of incidents responded to within the 300-second threshold.
	
5.	Spatial Analysis: Perform spatial analysis to examine the geographic distribution of fire incidents and assess the spatial variation in fire service efficiency across the region.

In [1]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
from pathlib import Path

In [2]:
# Current dir
cwd = Path(os.getcwd())

if cwd.name == "utils":
    BASE_DIR = cwd.parent
else:
    BASE_DIR = cwd

data_dir = BASE_DIR / "data"
data_dir.mkdir(exist_ok=True)

print("BASE_DIR:", BASE_DIR)
print("data_dir:", data_dir)

BASE_DIR: /Users/zhaoyuxin/Repos/fire_station_optimisation_ga
data_dir: /Users/zhaoyuxin/Repos/fire_station_optimisation_ga/data

### Load the data

In [3]:
incidents = pd.read_excel("Data/wmfs_incidents.xlsx")

In [4]:
incidents = incidents[incidents['incident_classification_level1'].isin(['FIRE', 'FALSE_ALARM'])]
incidents

,call_time,incident_classification_label,incident_profile_label,incident_classification_level1,prl_count,brv_count,EASTINGS,NORTHINGS,call_seconds,reaction_seconds,driving_seconds
0,2009-01-01 00:00:39,False alarm raised with good intent,False Alarms,FALSE_ALARM,2,0,392062.102010,286844.969007,86,160,250
1,2009-01-01 00:10:45,Secondary fire,Secondary Fires that attract a 20 minute-respo...,FIRE,1,0,405643.149442,277939.980158,85,65,239
2,2009-01-01 00:11:59,False alarm raised with malicious intent,False Alarms,FALSE_ALARM,1,0,410260.244387,288819.189377,62,106,115
3,2009-01-01 00:53:02,Secondary fire,Secondary Fires that attract a 20 minute-respo...,FIRE,1,0,396779.250331,299030.106069,72,109,96
4,2009-01-01 00:52:13,False alarm raised with malicious intent,False Alarms,FALSE_ALARM,1,0,410667.961350,290492.478579,68,109,204
...,...,...,...,...,...,...,...,...,...,...,...
383662,2023-12-31 22:59:53,False Alarms (Equipment),Low Risk,FALSE_ALARM,2,0,398666.686740,283225.457018,88,82,281
383663,2023-12-31 23:11:53,False alarm raised with good intent,False Alarms,FALSE_ALARM,1,1,433136.867808,277909.030728,134,94,98
383664,2023-12-31 23:32:10,Accidental secondary fire,Secondary Fires that attract a 20 minute-respo...,FIRE,0,1,401134.330416,277356.681953,136,152,227
383666,2023-12-31 23:49:50,False Alarms (Equipment),Low Risk,FALSE_ALARM,0,1,406221.058730,290654.181612,253,66,297
383667,2023-12-31 23:49:06,False Alarms (Equipment),Low Risk,FALSE_ALARM,2,1,416529.495310,285651.690157,218,71,177

In [5]:
incidents['total_response_time'] = incidents['reaction_seconds'] + incidents['driving_seconds']
incidents = incidents[(incidents['incident_classification_level1'] == 'FALSE_ALARM') | (incidents['incident_classification_level1'] == 'FIRE')]

In [6]:
# The threshold for response time in seconds
response_threshold = 300
# Add a new column: Whether the response time exceeds 300 seconds (1: exceeds, 0: not exceeds)
incidents['over_response_threshold'] = (incidents['total_response_time'] > response_threshold).astype(int)

incidents

,call_time,incident_classification_label,incident_profile_label,incident_classification_level1,prl_count,brv_count,EASTINGS,NORTHINGS,call_seconds,reaction_seconds,driving_seconds,total_response_time,over_response_threshold
0,2009-01-01 00:00:39,False alarm raised with good intent,False Alarms,FALSE_ALARM,2,0,392062.102010,286844.969007,86,160,250,410,1
1,2009-01-01 00:10:45,Secondary fire,Secondary Fires that attract a 20 minute-respo...,FIRE,1,0,405643.149442,277939.980158,85,65,239,304,1
2,2009-01-01 00:11:59,False alarm raised with malicious intent,False Alarms,FALSE_ALARM,1,0,410260.244387,288819.189377,62,106,115,221,0
3,2009-01-01 00:53:02,Secondary fire,Secondary Fires that attract a 20 minute-respo...,FIRE,1,0,396779.250331,299030.106069,72,109,96,205,0
4,2009-01-01 00:52:13,False alarm raised with malicious intent,False Alarms,FALSE_ALARM,1,0,410667.961350,290492.478579,68,109,204,313,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
383662,2023-12-31 22:59:53,False Alarms (Equipment),Low Risk,FALSE_ALARM,2,0,398666.686740,283225.457018,88,82,281,363,1
383663,2023-12-31 23:11:53,False alarm raised with good intent,False Alarms,FALSE_ALARM,1,1,433136.867808,277909.030728,134,94,98,192,0
383664,2023-12-31 23:32:10,Accidental secondary fire,Secondary Fires that attract a 20 minute-respo...,FIRE,0,1,401134.330416,277356.681953,136,152,227,379,1
383666,2023-12-31 23:49:50,False Alarms (Equipment),Low Risk,FALSE_ALARM,0,1,406221.058730,290654.181612,253,66,297,363,1
383667,2023-12-31 23:49:06,False Alarms (Equipment),Low Risk,FALSE_ALARM,2,1,416529.495310,285651.690157,218,71,177,248,0

### Aggregate the data into 500-m square grid

In [7]:
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point, Polygon
import numpy as np

# Read the data
incidents = gpd.GeoDataFrame(incidents, geometry=gpd.points_from_xy(incidents['EASTINGS'], incidents['NORTHINGS']))
# Set CRS for incidents and stations
incidents.set_crs(epsg=27700, inplace=True)
# Define the grid size
grid_size = 500
# Calculate the bounding box for the grid
xmin, ymin, xmax, ymax = incidents.total_bounds

# Calculate the bound
xmin = incidents['EASTINGS'].min() // grid_size * grid_size # // means quotient rounding
xmax = incidents['EASTINGS'].max() // grid_size * grid_size + grid_size # rounding down so another grid needs to be added
ymin = incidents['NORTHINGS'].min() // grid_size * grid_size
ymax = incidents['NORTHINGS'].max() // grid_size * grid_size + grid_size

In [8]:
# Create the grids for all of the cells 
x_coords = np.arange(xmin, xmax + grid_size, grid_size)
y_coords = np.arange(ymin, ymax + grid_size, grid_size)

grid_polygons = []
grid_ids = []

for i, x in enumerate(x_coords[:-1]):
    for j, y in enumerate(y_coords[:-1]):
        poly = Polygon([(x, y), (x + grid_size, y), (x + grid_size, y + grid_size), (x, y + grid_size)])
        grid_polygons.append(poly)
        grid_ids.append(f"{i}_{j}")

grid_gpd = gpd.GeoDataFrame({'grid_id': grid_ids, 'geometry': grid_polygons}, crs=incidents.crs)
# Construct the mapping table of grid_id -> grid_idx
grid_idx_map = pd.DataFrame({
    'grid_id': grid_gpd['grid_id'].values,
    'grid_idx': grid_gpd.index  
})

grid_gpd

     grid_id                                           geometry
0        0_0  POLYGON ((386000 272000, 386500 272000, 386500...
1        0_1  POLYGON ((386000 272500, 386500 272500, 386500...
2        0_2  POLYGON ((386000 273000, 386500 273000, 386500...
3        0_3  POLYGON ((386000 273500, 386500 273500, 386500...
4        0_4  POLYGON ((386000 274000, 386500 274000, 386500...
...      ...                                                ...
7592  106_66  POLYGON ((439000 305000, 439500 305000, 439500...
7593  106_67  POLYGON ((439000 305500, 439500 305500, 439500...
7594  106_68  POLYGON ((439000 306000, 439500 306000, 439500...
7595  106_69  POLYGON ((439000 306500, 439500 306500, 439500...
7596  106_70  POLYGON ((439000 307000, 439500 307000, 439500...

[7597 rows x 2 columns]

In [9]:
grid_idx_map

     grid_id  grid_idx
0        0_0         0
1        0_1         1
2        0_2         2
3        0_3         3
4        0_4         4
...      ...       ...
7592  106_66      7592
7593  106_67      7593
7594  106_68      7594
7595  106_69      7595
7596  106_70      7596

[7597 rows x 2 columns]

In [10]:
# Calculate the centroid of each grid 
grid_gpd['centroid'] = grid_gpd.geometry.centroid

In [11]:
# Ensure index_right does not exist before sjoin
incidents.drop(columns=['index_right'], errors='ignore', inplace=True)
# Perform spatial join
incidents = gpd.sjoin(incidents, grid_gpd, how="left", predicate="intersects")
#incidents.drop(columns=['grid_id_left'])

incidents

,call_time,incident_classification_label,incident_profile_label,incident_classification_level1,prl_count,brv_count,EASTINGS,NORTHINGS,call_seconds,reaction_seconds,driving_seconds,total_response_time,over_response_threshold,geometry,index_right,grid_id,centroid
0,2009-01-01 00:00:39,False alarm raised with good intent,False Alarms,FALSE_ALARM,2,0,392062.102010,286844.969007,86,160,250,410,1,POINT (392062.102 286844.969),881,12_29,POINT (392250 286750)
1,2009-01-01 00:10:45,Secondary fire,Secondary Fires that attract a 20 minute-respo...,FIRE,1,0,405643.149442,277939.980158,85,65,239,304,1,POINT (405643.149 277939.98),2780,39_11,POINT (405750 277750)
2,2009-01-01 00:11:59,False alarm raised with malicious intent,False Alarms,FALSE_ALARM,1,0,410260.244387,288819.189377,62,106,115,221,0,POINT (410260.244 288819.189),3441,48_33,POINT (410250 288750)
3,2009-01-01 00:53:02,Secondary fire,Secondary Fires that attract a 20 minute-respo...,FIRE,1,0,396779.250331,299030.106069,72,109,96,205,0,POINT (396779.25 299030.106),1545,21_54,POINT (396750 299250)
4,2009-01-01 00:52:13,False alarm raised with malicious intent,False Alarms,FALSE_ALARM,1,0,410667.961350,290492.478579,68,109,204,313,1,POINT (410667.961 290492.479),3515,49_36,POINT (410750 290250)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383662,2023-12-31 22:59:53,False Alarms (Equipment),Low Risk,FALSE_ALARM,2,0,398666.686740,283225.457018,88,82,281,363,1,POINT (398666.687 283225.457),1797,25_22,POINT (398750 283250)
383663,2023-12-31 23:11:53,False alarm raised with good intent,False Alarms,FALSE_ALARM,1,1,433136.867808,277909.030728,134,94,98,192,0,POINT (433136.868 277909.031),6685,94_11,POINT (433250 277750)
383664,2023-12-31 23:32:10,Accidental secondary fire,Secondary Fires that attract a 20 minute-respo...,FIRE,0,1,401134.330416,277356.681953,136,152,227,379,1,POINT (401134.33 277356.682),2140,30_10,POINT (401250 277250)
383666,2023-12-31 23:49:50,False Alarms (Equipment),Low Risk,FALSE_ALARM,0,1,406221.058730,290654.181612,253,66,297,363,1,POINT (406221.059 290654.182),2877,40_37,POINT (406250 290750)
383667,2023-12-31 23:49:06,False Alarms (Equipment),Low Risk,FALSE_ALARM,2,1,416529.495310,285651.690157,218,71,177,248,0,POINT (416529.495 285651.69),4358,61_27,POINT (416750 285750)

In [12]:
#  Grid index of all incidents
incidents = incidents.merge(grid_idx_map, on='grid_id', how='left')
incidents['grid_idx'] = incidents['grid_idx'].fillna(0).astype(int)
incidents.drop(columns=['index_right'], inplace=True)
incidents

,call_time,incident_classification_label,incident_profile_label,incident_classification_level1,prl_count,brv_count,EASTINGS,NORTHINGS,call_seconds,reaction_seconds,driving_seconds,total_response_time,over_response_threshold,geometry,grid_id,centroid,grid_idx
0,2009-01-01 00:00:39,False alarm raised with good intent,False Alarms,FALSE_ALARM,2,0,392062.102010,286844.969007,86,160,250,410,1,POINT (392062.102 286844.969),12_29,POINT (392250 286750),881
1,2009-01-01 00:10:45,Secondary fire,Secondary Fires that attract a 20 minute-respo...,FIRE,1,0,405643.149442,277939.980158,85,65,239,304,1,POINT (405643.149 277939.98),39_11,POINT (405750 277750),2780
2,2009-01-01 00:11:59,False alarm raised with malicious intent,False Alarms,FALSE_ALARM,1,0,410260.244387,288819.189377,62,106,115,221,0,POINT (410260.244 288819.189),48_33,POINT (410250 288750),3441
3,2009-01-01 00:53:02,Secondary fire,Secondary Fires that attract a 20 minute-respo...,FIRE,1,0,396779.250331,299030.106069,72,109,96,205,0,POINT (396779.25 299030.106),21_54,POINT (396750 299250),1545
4,2009-01-01 00:52:13,False alarm raised with malicious intent,False Alarms,FALSE_ALARM,1,0,410667.961350,290492.478579,68,109,204,313,1,POINT (410667.961 290492.479),49_36,POINT (410750 290250),3515
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292692,2023-12-31 22:59:53,False Alarms (Equipment),Low Risk,FALSE_ALARM,2,0,398666.686740,283225.457018,88,82,281,363,1,POINT (398666.687 283225.457),25_22,POINT (398750 283250),1797
292693,2023-12-31 23:11:53,False alarm raised with good intent,False Alarms,FALSE_ALARM,1,1,433136.867808,277909.030728,134,94,98,192,0,POINT (433136.868 277909.031),94_11,POINT (433250 277750),6685
292694,2023-12-31 23:32:10,Accidental secondary fire,Secondary Fires that attract a 20 minute-respo...,FIRE,0,1,401134.330416,277356.681953,136,152,227,379,1,POINT (401134.33 277356.682),30_10,POINT (401250 277250),2140
292695,2023-12-31 23:49:50,False Alarms (Equipment),Low Risk,FALSE_ALARM,0,1,406221.058730,290654.181612,253,66,297,363,1,POINT (406221.059 290654.182),40_37,POINT (406250 290750),2877
292696,2023-12-31 23:49:06,False Alarms (Equipment),Low Risk,FALSE_ALARM,2,1,416529.495310,285651.690157,218,71,177,248,0,POINT (416529.495 285651.69),61_27,POINT (416750 285750),4358

In [13]:
incident_counts = incidents.groupby('grid_idx').size().reset_index(name='fire_counts')
incident_counts

      grid_idx  fire_counts
0           51            1
1           52           10
2           53            4
3          122            7
4          123           15
...        ...          ...
3729      7473           48
3730      7474           30
3731      7475           13
3732      7544            4
3733      7545            6

[3734 rows x 2 columns]

#### Calculate the metrics: "in_time_response_rate" and "fire_frequency"

In [18]:
# Calculate the number of events and total number of events within 300s in each grid_id
metrics = incidents.groupby('grid_id')['over_response_threshold'].agg(
    fires_under_300=lambda x: np.sum(x == 0),  # Calculate the number of events with response time ≤ 300s
    fires_over_300=lambda x: np.sum(x == 1),  # Calculate the number of events with response time > 300s
    total_fires=lambda x: len(x)  # Calculate the total number of fire events in this grid
)

# Calculate the proportion  (avoid the error of 0)
metrics['in_time_response_rate'] = metrics['fires_under_300'] / metrics['total_fires']
metrics['fire_frequency'] = metrics['total_fires'] / len(incidents)  # Average number of fires per grid cell

metrics

,fires_under_300,fires_over_300,total_fires,in_time_response_rate,fire_frequency
grid_id,,,,,
0_51,0,1,1,0.000000,0.000003
0_52,0,10,10,0.000000,0.000034
0_53,0,4,4,0.000000,0.000014
100_10,32,99,131,0.244275,0.000448
100_11,55,48,103,0.533981,0.000352
...,...,...,...,...,...
9_59,0,27,27,0.000000,0.000092
9_60,5,37,42,0.119048,0.000143
9_61,3,60,63,0.047619,0.000215
9_62,4,55,59,0.067797,0.000202
9_63,0,9,9,0.000000,0.000031

In [19]:
if metrics.index.name == "grid_id":
    metrics = metrics.reset_index()

metrics_full = (
    grid_idx_map[['grid_id', 'grid_idx']]      
    .merge(metrics, on='grid_id', how='left')   
    .fillna(0)                               
)

metrics_full = metrics_full.sort_values('grid_idx').reset_index(drop=True)
metrics_full

,grid_id,grid_idx,fires_under_300,fires_over_300,total_fires,in_time_response_rate,fire_frequency
0,0_0,0,0.0,0.0,0.0,0.0,0.0
1,0_1,1,0.0,0.0,0.0,0.0,0.0
2,0_2,2,0.0,0.0,0.0,0.0,0.0
3,0_3,3,0.0,0.0,0.0,0.0,0.0
4,0_4,4,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
7592,106_66,7592,0.0,0.0,0.0,0.0,0.0
7593,106_67,7593,0.0,0.0,0.0,0.0,0.0
7594,106_68,7594,0.0,0.0,0.0,0.0,0.0
7595,106_69,7595,0.0,0.0,0.0,0.0,0.0
7596,106_70,7596,0.0,0.0,0.0,0.0,0.0

In [20]:
all_gdf = grid_gpd[["grid_id", "centroid"]].merge(
    metrics_full, on="grid_id", how="right"
)
all_gdf

,grid_id,centroid,grid_idx,fires_under_300,fires_over_300,total_fires,in_time_response_rate,fire_frequency
0,0_0,POINT (386250 272250),0,0.0,0.0,0.0,0.0,0.0
1,0_1,POINT (386250 272750),1,0.0,0.0,0.0,0.0,0.0
2,0_2,POINT (386250 273250),2,0.0,0.0,0.0,0.0,0.0
3,0_3,POINT (386250 273750),3,0.0,0.0,0.0,0.0,0.0
4,0_4,POINT (386250 274250),4,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
7592,106_66,POINT (439250 305250),7592,0.0,0.0,0.0,0.0,0.0
7593,106_67,POINT (439250 305750),7593,0.0,0.0,0.0,0.0,0.0
7594,106_68,POINT (439250 306250),7594,0.0,0.0,0.0,0.0,0.0
7595,106_69,POINT (439250 306750),7595,0.0,0.0,0.0,0.0,0.0
7596,106_70,POINT (439250 307250),7596,0.0,0.0,0.0,0.0,0.0

In [23]:
gdf_out = all_gdf[["grid_id", "centroid", "grid_idx"]]

# 保存为 Shapefile
gdf_out.to_file(data_dir / "output.shp", driver="ESRI Shapefile")

In [18]:
# Extract as NumPy array (cells, 2)
xy_all = np.vstack([
    all_gdf['centroid'].x.values,
    all_gdf['centroid'].y.values
]).T    # shape: (num_cells, 2)

# Save as xy_all.npy
np.save(data_dir / "xy_all.npy", xy_all)

print(" xy_all is complete，shape =", xy_all.shape)
xy_all

 xy_all is complete，shape = (7597, 2)

array([[386250., 272250.],
       [386250., 272750.],
       [386250., 273250.],
       ...,
       [439250., 306250.],
       [439250., 306750.],
       [439250., 307250.]])

In [19]:
fire_frequency = metrics_full['fire_frequency'].to_numpy()
fire_frequency

array([0., 0., 0., ..., 0., 0., 0.])

#### Save result data

In [20]:
# Save the centroid of all grids
xy_all = np.vstack([
    grid_gpd['centroid'].x.values,
    grid_gpd['centroid'].y.values
]).T    # shape: (num_cells, 2)

# Save as xy_all.npy
np.save(data_dir / "xy_all.npy", xy_all)

print(" xy_all is complete，shape =", xy_all.shape)
xy_all

 xy_all is complete，shape = (7597, 2)

array([[386250., 272250.],
       [386250., 272750.],
       [386250., 273250.],
       ...,
       [439250., 306250.],
       [439250., 306750.],
       [439250., 307250.]])

In [21]:
# Save the incident frequency data
incident_freq = metrics_full['fire_frequency'].values
np.save(data_dir / "incident_freq.npy", incident_freq)
print(data_dir / "incident_freq.npy")

/Users/zhaoyuxin/Repos/fire_station_optimisation_ga/data/incident_freq.npy

In [ ]:
# Save the index data
index_book = metrics_full[["grid_idx", "grid_id"]].drop_duplicates().sort_values("grid_idx").reset_index(drop=True)
index_book.to_parquet(data_dir / "all_index_book.parquet", index=False)

### Features of the index without the distance and number of the stations within a specific distance ###

In [23]:
features = pd.read_csv(data_dir / "All_features_1.csv")
features

,grid_id,in_time_response_rate,nearest_station_travel_time,"Accommodation, eating and drinking",Attractions,Commercial services,Education and health,Manufacturing and production,Public infrastructure,Retail,...,Low density residential with amenities (suburbs and small villages / hamlets),Medium density residential with high streets and amenities,Mining and spoil areas,Open or heath and moor land,Orchards,Principle Transport,Recreational land,Retail parks,Urban centres - mainly commercial/retail with residential pockets,Wetlands
0,0_51,0.000000,458.000000,0,0,0,0,0,0,0,...,1.56,0.000000e+00,0.0,0.0,0.0,1.340000e-09,0.00,0.0,0.0,0.0
1,0_52,0.000000,436.100000,0,0,0,1,0,1,0,...,29.52,3.960000e+00,0.0,0.0,0.0,5.560000e+00,0.00,0.0,0.0,0.0
2,0_53,0.000000,408.250000,0,1,0,1,1,1,0,...,40.48,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.00,0.0,0.0,0.0
3,100_10,0.244275,288.519084,0,2,1,2,0,4,0,...,5.20,1.790000e-09,0.0,0.0,0.0,9.840000e+00,31.96,0.0,0.0,0.0
4,100_11,0.533981,160.514563,0,1,3,0,0,1,0,...,17.16,3.192000e+01,0.0,0.0,0.0,6.920000e+00,8.32,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3729,9_59,0.000000,373.814815,0,0,2,1,1,1,1,...,21.88,1.996000e+01,0.0,0.0,0.0,0.000000e+00,36.76,0.0,0.0,0.0
3730,9_60,0.119048,406.761905,0,0,13,2,2,3,2,...,0.36,7.764000e+01,0.0,0.0,0.0,0.000000e+00,1.08,0.0,0.0,0.0
3731,9_61,0.047619,404.190476,0,1,1,1,0,5,0,...,16.36,2.872000e+01,0.0,0.0,0.0,0.000000e+00,0.44,0.0,0.0,0.0
3732,9_62,0.067797,430.406780,3,1,4,0,0,5,1,...,6.80,4.696000e+01,0.0,0.0,0.0,0.000000e+00,30.80,0.0,0.0,0.0
3733,9_63,0.000000,515.666667,0,0,4,0,1,10,0,...,1.08,1.800000e+00,0.0,0.0,0.0,0.000000e+00,2.80,0.0,0.0,0.0

In [24]:
features_full = grid_idx_map.merge(features, on='grid_id', how='left')
features_full

,grid_id,grid_idx,in_time_response_rate,nearest_station_travel_time,"Accommodation, eating and drinking",Attractions,Commercial services,Education and health,Manufacturing and production,Public infrastructure,...,Low density residential with amenities (suburbs and small villages / hamlets),Medium density residential with high streets and amenities,Mining and spoil areas,Open or heath and moor land,Orchards,Principle Transport,Recreational land,Retail parks,Urban centres - mainly commercial/retail with residential pockets,Wetlands
0,0_0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0_1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0_2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0_3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0_4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7592,106_66,7592,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7593,106_67,7593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7594,106_68,7594,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7595,106_69,7595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7596,106_70,7596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
features_full = features_full.fillna(0)

In [26]:
partial_features = features_full[['neighbour_frequency_per_month', 
           'Agriculture - mainly crops', 
           'Deciduous woodland']]
     #      'station_count']]
partial_features

,neighbour_frequency_per_month,Agriculture - mainly crops,Deciduous woodland
0,0.0,0.0,0.0
1,0.0,0.0,0.0
2,0.0,0.0,0.0
3,0.0,0.0,0.0
4,0.0,0.0,0.0
...,...,...,...
7592,0.0,0.0,0.0
7593,0.0,0.0,0.0
7594,0.0,0.0,0.0
7595,0.0,0.0,0.0
7596,0.0,0.0,0.0

In [27]:
np.save(data_dir / "features_full.npy", features_full.values)
np.save(data_dir / "partial_features.npy", partial_features.values)